# Generated by Django 2.0.5 on 2018-05-19 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('tenants', '0001_initial'), ('tenants', '0002_auto_20180517_2313'), ('tenants', '0003_supportstaffuser_role'), ('tenants', '0004_remove_staffuser_is_admin')]

    initial = True

    dependencies = [
        ('users', '0002_user_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='PrimaryStaffUser',
            fields=[
                ('staffuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.StaffUser')),
                ('rank', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tenants.staffuser',),
        ),
        migrations.CreateModel(
            name='SupportStaffUser',
            fields=[
                ('staffuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.StaffUser')),
                ('role', models.PositiveIntegerField(choices=[(1, 'assistant'), (2, 'bodyguard'), (3, 'billing manager'), (4, 'mentor')], default=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tenants.staffuser',),
        ),
        migrations.AddField(
            model_name='primarystaffuser',
            name='team',
            field=models.ManyToManyField(blank=True, to='tenants.SupportStaffUser'),
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='is_admin',
        ),
    ]
