# Generated by Django 2.0.5 on 2018-05-17 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportstaffuser',
            name='role',
        ),
        migrations.DeleteModel(
            name='SupportRole',
        ),
    ]
