# Generated by Django 2.0.5 on 2018-05-17 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_supportstaffuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='is_admin',
        ),
    ]
